name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, copilot/fix-* ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run lint
      run: npm run lint --if-present
      
    - name: Build application
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Copy frontend files
      run: |
        mkdir -p _site
        cp -r frontend/* _site/
        
        # Create a basic server.js for static hosting
        cat > _site/server.js << 'EOF'
        // Static server for GitHub Pages
        const express = require('express');
        const path = require('path');
        
        const app = express();
        const PORT = process.env.PORT || 3000;
        
        // Serve static files
        app.use(express.static(path.join(__dirname)));
        
        // SPA routing - serve index.html for all routes
        app.get('*', (req, res) => {
          res.sendFile(path.join(__dirname, 'index.html'));
        });
        
        app.listen(PORT, () => {
          console.log(`Server running on port ${PORT}`);
        });
        EOF
        
        # Update API base URL for production
        sed -i "s|http://localhost:3000/api|https://api.yourdomain.com/api|g" _site/js/utils.js
        
        # Add _config.yml for Jekyll
        cat > _site/_config.yml << 'EOF'
        include:
          - .htaccess
        exclude:
          - node_modules
          - package*.json
          - backend
          - database
        plugins:
          - jekyll-sitemap
        EOF
        
        # Add .nojekyll to disable Jekyll processing
        touch _site/.nojekyll
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/copilot/fix-')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4